### ISSUE TITLE
License

### ISSUE THREAD

**Issue by varmaricha** [SRI-CSL/secure_ros#10]
Could you please add a license (MIT or Apache for opensource use) in your repository? 
Thanks a lot in advance.

**Comment by asundaresan** [comment]
Hello: This project is actually a meta-package that is basically a fork of two existing projects: `ros_comm` and `nodelet_core`. As such, the license is the same as those projects (BSD).

**Comment by asundaresan** [comment]
I've added a BSD license file explicitly to this repository. Please let me know if this works for you.
